CREATE TABLE "Users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "firstName" varchar(20) NOT NULL,
    "lastName" varchar(20) NOT NULL,
    "email" varchar(30) UNIQUE NOT NULL,
    "username" varchar(18) UNIQUE NOT NULL,
    "passwordHash" char(64) NOT NULL,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE TABLE "Spots" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "ownerId" integer,
    "address" varchar NOT NULL,
    "city" varchar NOT NULL,
    "state" varchar NOT NULL,
    "country" varchar NOT NULL,
    "lat" numeric,
    "lng" numeric,
    "name" varchar(50),
    "description" varchar NOT NULL,
    "price" numeric(0, 2) NOT NULL,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE TABLE "SpotImages" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "spotId" integer,
    "url" varchar,
    "preview" boolean,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE TABLE "Reviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "userId" integer NOT NULL,
    "spotId" integer NOT NULL,
    "review" varchar NOT NULL,
    "stars" integer NOT NULL,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE TABLE "ReviewImages" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "reviewId" integer NOT NULL,
    "url" varchar,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE TABLE "Bookings" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "spotId" integer NOT NULL,
    "userId" integer NOT NULL,
    "startDate" date,
    "endDate" date,
    "createdAt" datetime DEFAULT (NOW()),
    "updatedAt" datetime DEFAULT (NOW())
);

CREATE UNIQUE INDEX ON "Reviews" ("userId", "spotId");

CREATE UNIQUE INDEX ON "Bookings" ("spotId", "startDate");

CREATE UNIQUE INDEX ON "Bookings" ("spotId", "endDate");

ALTER TABLE
    "Spots"
ADD
    FOREIGN KEY ("ownerId") REFERENCES "Users" ("id");

ALTER TABLE
    "SpotImages"
ADD
    FOREIGN KEY ("spotId") REFERENCES "Spots" ("id");

ALTER TABLE
    "Reviews"
ADD
    FOREIGN KEY ("userId") REFERENCES "Users" ("id");

ALTER TABLE
    "Reviews"
ADD
    FOREIGN KEY ("spotId") REFERENCES "Spots" ("id");

ALTER TABLE
    "ReviewImages"
ADD
    FOREIGN KEY ("reviewId") REFERENCES "Reviews" ("id");

ALTER TABLE
    "Bookings"
ADD
    FOREIGN KEY ("spotId") REFERENCES "Spots" ("id");

ALTER TABLE
    "Bookings"
ADD
    FOREIGN KEY ("userId") REFERENCES "Users" ("id");
